CREATE TABLE "admin_api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_api_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"admin_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"token_hash" char(64) NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"expira_em" timestamp NOT NULL,
	CONSTRAINT "admin_api_tokens_uq_token_hash" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "admins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(100),
	"usuario" varchar(50),
	"perfil" varchar(30) DEFAULT 'admin' NOT NULL,
	"email" varchar(100),
	"senha" varchar(255),
	"codigo_acesso" varchar(10),
	"google_id" varchar(64),
	"ativo" boolean DEFAULT true,
	"criado_em" timestamp DEFAULT now(),
	"reset_token" varchar(255),
	"reset_expira" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"foto" varchar(255),
	CONSTRAINT "admins_email" UNIQUE("email"),
	CONSTRAINT "admins_usuario" UNIQUE("usuario"),
	CONSTRAINT "admins_idx_admins_codigo_acesso" UNIQUE("codigo_acesso")
);
--> statement-breakpoint
CREATE TABLE "assinaturas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assinaturas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"plano_id" integer NOT NULL,
	"status" text DEFAULT 'trial' NOT NULL,
	"trial_inicio" date,
	"trial_fim" date,
	"ciclo_inicio" date,
	"ciclo_fim" date,
	"bloqueada_em" timestamp,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "avaliacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "avaliacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"cliente_id" integer,
	"nota" smallint NOT NULL,
	"descricao" text,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "avaliacoes_uq_pedido" UNIQUE("pedido_id","loja_id")
);
--> statement-breakpoint
CREATE TABLE "caixa_movimentacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caixa_movimentacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"caixa_id" integer NOT NULL,
	"operador_id" integer NOT NULL,
	"tipo" text NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"observacoes" varchar(120),
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "caixa_turnos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caixa_turnos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operador_id" integer,
	"status" text DEFAULT 'aberto' NOT NULL,
	"saldo_inicial" numeric(10, 2) DEFAULT 0 NOT NULL,
	"saldo_final" numeric(10, 2),
	"aberto_em" timestamp DEFAULT now() NOT NULL,
	"fechado_em" timestamp,
	"obs_abertura" text,
	"obs_fechamento" text,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cashback_movimentacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cashback_movimentacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cliente_id" integer NOT NULL,
	"pedido_id" integer,
	"tipo" text NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"saldo_antes" numeric(10, 2) DEFAULT 0 NOT NULL,
	"saldo_depois" numeric(10, 2) DEFAULT 0 NOT NULL,
	"expira_em" date,
	"disponivel_em" timestamp,
	"referencia_id" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categorias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categorias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(100),
	"ordem" integer DEFAULT 0,
	"ativo" boolean DEFAULT true,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"modo_exibicao" varchar(20) DEFAULT 'vertical' NOT NULL,
	"dias_semana" text,
	"horario_ini" varchar(5),
	"horario_fim" varchar(5)
);
--> statement-breakpoint
CREATE TABLE "clientes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clientes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(100),
	"telefone" varchar(20),
	"endereco" text,
	"criado_em" timestamp DEFAULT now(),
	"email" varchar(150),
	"pontos" integer DEFAULT 0,
	"nivel" text DEFAULT 'Bronze',
	"aniversario" date,
	"cep" varchar(20),
	"rua" varchar(255),
	"numero" varchar(20),
	"bairro" varchar(100),
	"cidade" varchar(100),
	"estado" varchar(50),
	"complemento" varchar(255),
	"cashback_saldo" numeric(10, 2) DEFAULT 0 NOT NULL,
	"pontos_saldo" integer DEFAULT 0 NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"saldo_fiado" numeric(10, 2) DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cobrancas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cobrancas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assinatura_id" integer NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"vencimento" date NOT NULL,
	"status" text DEFAULT 'pendente' NOT NULL,
	"pago_em" timestamp,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"comprovante_arquivo" varchar(255),
	"comprovante_enviado_em" timestamp,
	"motivo_rejeicao" varchar(255),
	"origem" text DEFAULT 'manual' NOT NULL,
	"mp_payment_id" varchar(64),
	"mp_qr_code" text,
	"mp_qr_code_base64" text,
	"mp_expiracao" timestamp,
	CONSTRAINT "cobrancas_uq_cobrancas_mp_payment_id" UNIQUE("mp_payment_id")
);
--> statement-breakpoint
CREATE TABLE "combo_passo_opcoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combo_passo_opcoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"passo_id" integer NOT NULL,
	"combo_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"produto_id" integer NOT NULL,
	"preco_adicional" numeric(10, 2) DEFAULT 0 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"ordem" integer
);
--> statement-breakpoint
CREATE TABLE "combo_passos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combo_passos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"combo_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"nome" varchar(255) NOT NULL,
	"descricao" text,
	"obrigatorio" boolean DEFAULT true NOT NULL,
	"min_itens" integer DEFAULT 1 NOT NULL,
	"max_itens" integer DEFAULT 1 NOT NULL,
	"permite_repetir" boolean DEFAULT false NOT NULL,
	"ordem" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "combos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"categoria_id" integer,
	"nome" varchar(255) NOT NULL,
	"descricao" text,
	"imagem" varchar(500),
	"tipo_preco" text DEFAULT 'por_combo' NOT NULL,
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"preco_promocional" numeric(10, 2),
	"promo_desativado" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"ordem" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "complementos_grupos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complementos_grupos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"descricao" varchar(255),
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"opcional" boolean DEFAULT true NOT NULL,
	"obrigatorio" boolean DEFAULT false NOT NULL,
	"quantidade_minima" integer DEFAULT 0 NOT NULL,
	"quantidade_maxima" integer DEFAULT 0 NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "complementos_grupos_categorias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complementos_grupos_categorias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grupo_id" integer NOT NULL,
	"categoria_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "complementos_grupos_categorias_uniq_comp_grupo_cat" UNIQUE("grupo_id","categoria_id")
);
--> statement-breakpoint
CREATE TABLE "complementos_grupos_produtos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complementos_grupos_produtos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grupo_id" integer NOT NULL,
	"produto_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "complementos_grupos_produtos_uniq_comp_grupo_prod" UNIQUE("grupo_id","produto_id")
);
--> statement-breakpoint
CREATE TABLE "complementos_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complementos_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grupo_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"descricao" varchar(255),
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"pode_repetir" boolean DEFAULT true NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"ordem" integer DEFAULT 0 NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "configuracoes" (
	"chave" varchar(50) NOT NULL,
	"valor" text NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "configuracoes_loja_id_chave_pk" PRIMARY KEY("loja_id","chave")
);
--> statement-breakpoint
CREATE TABLE "cupons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cupons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(15) NOT NULL,
	"tipo" text DEFAULT 'percent' NOT NULL,
	"desconto" numeric(10, 2) DEFAULT 0 NOT NULL,
	"minimo" numeric(10, 2) DEFAULT 0 NOT NULL,
	"quantidade_total" integer DEFAULT 0 NOT NULL,
	"quantidade_usada" integer DEFAULT 0 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"primeira_compra" boolean DEFAULT false NOT NULL,
	"publico" boolean DEFAULT false NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "cupons_codigo" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "entrada_saida_bancos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entrada_saida_bancos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"nome" varchar(120) NOT NULL,
	"saldo_atual" numeric(10, 2) DEFAULT 0 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "entrada_saida_categorias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entrada_saida_categorias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"nome" varchar(120) NOT NULL,
	"tipo" text DEFAULT 'ambos' NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entrada_saida_categorias_uniq_entrada_saida_categoria_loja_nome" UNIQUE("loja_id","nome")
);
--> statement-breakpoint
CREATE TABLE "entrada_saida_formas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entrada_saida_formas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"nome" varchar(120) NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entrada_saida_formas_uniq_entrada_saida_forma_loja_nome" UNIQUE("loja_id","nome")
);
--> statement-breakpoint
CREATE TABLE "entrada_saida_lancamentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entrada_saida_lancamentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"tipo" text DEFAULT 'entrada' NOT NULL,
	"data_lancamento" date NOT NULL,
	"descricao" varchar(180) NOT NULL,
	"quantidade" integer DEFAULT 1 NOT NULL,
	"desconto" numeric(10, 2) DEFAULT 0 NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"forma_id" integer,
	"categoria_id" integer,
	"subcategoria_id" integer,
	"banco_id" integer,
	"criado_por" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "entrada_saida_subcategorias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entrada_saida_subcategorias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"categoria_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entrada_saida_subcategorias_uniq_entrada_saida_subcategoria_loj" UNIQUE("loja_id","categoria_id","nome")
);
--> statement-breakpoint
CREATE TABLE "estoque" (
	"produto_id" integer PRIMARY KEY NOT NULL,
	"quantidade" integer DEFAULT 0 NOT NULL,
	"atualizado_em" timestamp DEFAULT now(),
	"quantidade_minima" integer DEFAULT 0 NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "estoque_grupo_membros" (
	"produto_id" integer PRIMARY KEY NOT NULL,
	"grupo_id" integer NOT NULL,
	"loja_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "estoque_grupos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "estoque_grupos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "estoque_movimentacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "estoque_movimentacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"produto_id" integer NOT NULL,
	"tipo" text NOT NULL,
	"quantidade" integer NOT NULL,
	"origem" varchar(50),
	"referencia_id" integer,
	"criado_em" timestamp DEFAULT now(),
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fiado_lancamentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fiado_lancamentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"cliente_id" integer NOT NULL,
	"pedido_id" integer,
	"operador_id" integer,
	"tipo" text NOT NULL,
	"forma_pagamento" varchar(30),
	"valor" numeric(10, 2) NOT NULL,
	"saldo_antes" numeric(10, 2) DEFAULT 0 NOT NULL,
	"saldo_depois" numeric(10, 2) DEFAULT 0 NOT NULL,
	"observacao" varchar(255),
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "financial_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "financial_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer DEFAULT 1 NOT NULL,
	"name" varchar(160) NOT NULL,
	"initial_balance" numeric(14, 2) DEFAULT 0 NOT NULL,
	"current_balance" numeric(14, 2) DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	CONSTRAINT "financial_accounts_uniq_financial_accounts_tenant_name" UNIQUE("tenant_id","name")
);
--> statement-breakpoint
CREATE TABLE "financial_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "financial_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer DEFAULT 1 NOT NULL,
	"name" varchar(160) NOT NULL,
	"type" text NOT NULL,
	"parent_id" integer,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	CONSTRAINT "financial_categories_uniq_financial_categories_tenant_name_type" UNIQUE("tenant_id","name","type","parent_id")
);
--> statement-breakpoint
CREATE TABLE "financial_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "financial_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer DEFAULT 1 NOT NULL,
	"order_id" integer,
	"account_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	"payment_method_id" integer,
	"type" text NOT NULL,
	"description" varchar(255) NOT NULL,
	"amount" numeric(14, 2) DEFAULT 0 NOT NULL,
	"transaction_date" date NOT NULL,
	"reference_month" smallint NOT NULL,
	"reference_year" smallint NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	CONSTRAINT "financial_transactions_uniq_financial_transactions_sale_payment" UNIQUE("tenant_id","order_id","payment_method_id","type")
);
--> statement-breakpoint
CREATE TABLE "garcons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "garcons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"email" varchar(150) NOT NULL,
	"codigo_acesso_hash" varchar(255) NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "garcons_uq_garcom_loja_email" UNIQUE("loja_id","email")
);
--> statement-breakpoint
CREATE TABLE "landing_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "landing_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chave" varchar(80) NOT NULL,
	"valor" text NOT NULL,
	"atualizado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "landing_config_uniq_chave" UNIQUE("chave")
);
--> statement-breakpoint
CREATE TABLE "leads_especialista" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "leads_especialista_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(160) NOT NULL,
	"email" varchar(160) NOT NULL,
	"telefone" varchar(30) NOT NULL,
	"empresa" varchar(160) NOT NULL,
	"faturamento" varchar(120),
	"modelo_negocio" varchar(120),
	"aceite_whatsapp" boolean DEFAULT false NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leads_lojas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "leads_lojas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(160) NOT NULL,
	"empresa" varchar(160) NOT NULL,
	"email" varchar(160) NOT NULL,
	"whatsapp" varchar(30) NOT NULL,
	"cnpj" varchar(20) NOT NULL,
	"cep" varchar(12) NOT NULL,
	"rua" varchar(160) NOT NULL,
	"numero" varchar(20) NOT NULL,
	"bairro" varchar(120) NOT NULL,
	"cidade" varchar(120) NOT NULL,
	"estado" varchar(10) NOT NULL,
	"complemento" varchar(160),
	"faturamento" varchar(120),
	"segmento" varchar(120),
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listas_transmissao" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listas_transmissao_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"nome" varchar(160) NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "listas_transmissao_envios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listas_transmissao_envios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lista_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"mensagem" text NOT NULL,
	"total_destinatarios" integer DEFAULT 0 NOT NULL,
	"total_enviados" integer DEFAULT 0 NOT NULL,
	"total_falhas" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'em_andamento' NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"finalizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "listas_transmissao_membros" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listas_transmissao_membros_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lista_id" integer NOT NULL,
	"cliente_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "listas_transmissao_membros_uq_lista_cliente" UNIQUE("lista_id","cliente_id")
);
--> statement-breakpoint
CREATE TABLE "loja_eventos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "loja_eventos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"tipo" varchar(20) NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"visitante" varchar(40)
);
--> statement-breakpoint
CREATE TABLE "lojas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lojas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(100),
	"whatsapp" varchar(20),
	"endereco" text,
	"horario_funcionamento" varchar(100),
	"ativo" boolean DEFAULT true,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"plano_id" integer
);
--> statement-breakpoint
CREATE TABLE "materia_prima_cadastros" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "materia_prima_cadastros_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"nome_produto" varchar(180) NOT NULL,
	"data_compra" date NOT NULL,
	"valor_unitario" numeric(10, 2) DEFAULT 0 NOT NULL,
	"quantidade" numeric(10, 3) DEFAULT 1 NOT NULL,
	"unidade" varchar(40) DEFAULT 'unidade' NOT NULL,
	"desconto" numeric(10, 2) DEFAULT 0 NOT NULL,
	"categoria_id" integer,
	"subcategoria_id" integer,
	"fornecedor" varchar(160),
	"observacao" text,
	"valor_total" numeric(10, 2) DEFAULT 0 NOT NULL,
	"criado_por" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "mesas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mesas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"nome" varchar(60) NOT NULL,
	"cliente_id" integer,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "motoboys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "motoboys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"nome" varchar(160) NOT NULL,
	"whatsapp" varchar(30) NOT NULL,
	"data_cadastro" date NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "notificacoes_broadcast" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notificacoes_broadcast_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"titulo" varchar(160) NOT NULL,
	"mensagem" text NOT NULL,
	"imagem" varchar(255),
	"link" varchar(500),
	"status" text DEFAULT 'rascunho' NOT NULL,
	"agendado_para" timestamp,
	"enviado_em" timestamp,
	"criado_por" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notificacoes_broadcast_visualizacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notificacoes_broadcast_visualizacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"notificacao_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"visualizado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "notificacoes_broadcast_visualizacoes_uq_notif_loja" UNIQUE("notificacao_id","loja_id")
);
--> statement-breakpoint
CREATE TABLE "operacao_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "operacao_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operador_id" integer,
	"acao" varchar(60) NOT NULL,
	"referencia" varchar(60),
	"dados" text,
	"criado_em" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "orcamento_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orcamento_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orcamento_id" integer NOT NULL,
	"produto_id" integer,
	"nome" varchar(191) NOT NULL,
	"preco" numeric(10, 2) NOT NULL,
	"qtd" integer NOT NULL,
	"observacoes" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "orcamentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orcamentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"status" text DEFAULT 'pendente' NOT NULL,
	"cliente_nome" varchar(191) NOT NULL,
	"cliente_tipo_documento" text DEFAULT 'fisica' NOT NULL,
	"cliente_documento" varchar(30),
	"cliente_whatsapp" varchar(30),
	"cliente_endereco" text,
	"desconto_tipo" text DEFAULT 'valor' NOT NULL,
	"desconto_valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"subtotal" numeric(10, 2) DEFAULT 0 NOT NULL,
	"total" numeric(10, 2) DEFAULT 0 NOT NULL,
	"admin_id" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "pausas_programadas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pausas_programadas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"titulo" varchar(100) NOT NULL,
	"data_inicio" date NOT NULL,
	"hora_inicio" time NOT NULL,
	"data_fim" date NOT NULL,
	"hora_fim" time NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payment_methods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_methods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenant_id" integer DEFAULT 1 NOT NULL,
	"name" varchar(120) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	CONSTRAINT "payment_methods_uniq_payment_methods_tenant_name" UNIQUE("tenant_id","name")
);
--> statement-breakpoint
CREATE TABLE "pdv_reservas" (
	"loja_id" integer NOT NULL,
	"sessao" varchar(64) NOT NULL,
	"produto_id" integer NOT NULL,
	"quantidade" integer NOT NULL,
	"atualizado_em" timestamp NOT NULL,
	CONSTRAINT "pdv_reservas_loja_id_sessao_produto_id_pk" PRIMARY KEY("loja_id","sessao","produto_id")
);
--> statement-breakpoint
CREATE TABLE "pedido_combo_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_combo_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer NOT NULL,
	"pedido_item_id" integer NOT NULL,
	"produto_id" integer NOT NULL,
	"quantidade" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pedido_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer,
	"produto_nome" varchar(150),
	"quantidade" integer,
	"preco" numeric(10, 2),
	"observacoes" text,
	"cross_sell" boolean DEFAULT false NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"produto_id" integer
);
--> statement-breakpoint
CREATE TABLE "pedido_pagamentos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_pagamentos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer NOT NULL,
	"forma" varchar(30) NOT NULL,
	"valor" numeric(10, 2) NOT NULL,
	"taxa_maquininha" numeric(10, 2) DEFAULT 0 NOT NULL,
	"criado_em" timestamp DEFAULT now(),
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pedido_status_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_status_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_id" integer NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"status" varchar(20) NOT NULL,
	"criado_em" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "pedidos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedidos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"codigo" varchar(64),
	"cliente_id" integer,
	"mesa_id" integer,
	"garcom_id" integer,
	"motoboy_id" integer,
	"operador_id" integer,
	"caixa_id" integer,
	"offline_uuid" varchar(36),
	"tipo_entrega" text,
	"taxa_entrega" numeric(10, 2),
	"total" numeric(10, 2),
	"criado_em" timestamp DEFAULT now(),
	"tipo" text DEFAULT 'retirada' NOT NULL,
	"endereco_entrega" text,
	"subtotal" numeric(10, 2) DEFAULT 0 NOT NULL,
	"desconto" numeric(10, 2) DEFAULT 0 NOT NULL,
	"forma_pagamento" varchar(30) DEFAULT 'pix' NOT NULL,
	"valor_pago" numeric(10, 2),
	"troco" numeric(10, 2),
	"status" text DEFAULT 'pendente' NOT NULL,
	"origem" varchar(20),
	"updated_at" timestamp DEFAULT now(),
	"cupom" varchar(60),
	"taxa_maquininha" numeric(10, 2) DEFAULT 0 NOT NULL,
	"cashback_valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"cashback_percentual" numeric(5, 2) DEFAULT 0 NOT NULL,
	"cashback_expira_em" date,
	"cashback_aplicado" boolean DEFAULT false NOT NULL,
	"agendamento" timestamp,
	"observacoes_cliente" varchar(255),
	"loja_id" integer DEFAULT 1 NOT NULL,
	"cashback_usado" numeric(10, 2) DEFAULT 0 NOT NULL,
	CONSTRAINT "pedidos_idx_pedidos_offline_uuid" UNIQUE("offline_uuid")
);
--> statement-breakpoint
CREATE TABLE "permissoes_niveis" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissoes_niveis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(80) NOT NULL,
	"slug" varchar(80) NOT NULL,
	"permissoes_json" text NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	CONSTRAINT "permissoes_niveis_slug" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "permissoes_usuarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissoes_usuarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"permissao_id" integer NOT NULL,
	"admin_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "permissoes_usuarios_uniq_perm_usuario" UNIQUE("permissao_id","admin_id")
);
--> statement-breakpoint
CREATE TABLE "planos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "planos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"periodicidade" text DEFAULT 'mensal' NOT NULL,
	"dias_trial" integer DEFAULT 15 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"landing_slug" varchar(20),
	"recursos_json" text,
	CONSTRAINT "planos_uq_planos_landing_slug" UNIQUE("landing_slug")
);
--> statement-breakpoint
CREATE TABLE "pontos_movimentacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pontos_movimentacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cliente_id" integer NOT NULL,
	"pedido_id" integer,
	"tipo" text NOT NULL,
	"pontos" integer DEFAULT 0 NOT NULL,
	"saldo_antes" integer DEFAULT 0 NOT NULL,
	"saldo_depois" integer DEFAULT 0 NOT NULL,
	"referencia_id" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "produto_complementos_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produto_complementos_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"produto_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"obrigatorio" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"ordem" integer DEFAULT 0 NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp
);
--> statement-breakpoint
CREATE TABLE "produto_extras" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produto_extras_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"produto_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"obrigatorio" boolean DEFAULT false NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"ordem" integer DEFAULT 0 NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "produto_variacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produto_variacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"produto_id" integer NOT NULL,
	"tamanho" varchar(60),
	"cor" varchar(60),
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"ordem" integer DEFAULT 0 NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "produtos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produtos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer,
	"nome" varchar(150),
	"descricao" text,
	"preco" numeric(10, 2),
	"pontos_ganho" integer DEFAULT 0 NOT NULL,
	"pontos_custo" integer DEFAULT 0 NOT NULL,
	"imagem" varchar(255),
	"ativo" boolean DEFAULT true,
	"ordem" integer,
	"preco_promocional" numeric(10, 2),
	"promo_desativado" boolean DEFAULT true NOT NULL,
	"tem_variacoes" boolean DEFAULT false NOT NULL,
	"disponivel_catalogo" boolean DEFAULT true NOT NULL,
	"disponivel_mesa" boolean DEFAULT true NOT NULL,
	"loja_id" integer DEFAULT 1 NOT NULL,
	"apenas_agendamento" boolean DEFAULT false NOT NULL,
	"quantidade_minima" integer DEFAULT 0 NOT NULL,
	"dias_semana" text,
	"horario_ini" varchar(5),
	"horario_fim" varchar(5),
	"data_fabricacao" date,
	"data_validade" date,
	"promo_dias" integer,
	"promo_inicio" date,
	"promo_imagem" varchar(255),
	"promo_descricao" text,
	"promo_etiqueta" varchar(30),
	"destaque" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "suporte_digitando" (
	"loja_id" integer NOT NULL,
	"quem" text NOT NULL,
	"atualizado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "suporte_digitando_loja_id_quem_pk" PRIMARY KEY("loja_id","quem")
);
--> statement-breakpoint
CREATE TABLE "suporte_mensagens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "suporte_mensagens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"remetente" text NOT NULL,
	"mensagem" text NOT NULL,
	"lida_loja" boolean DEFAULT false NOT NULL,
	"lida_suporte" boolean DEFAULT false NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"anexo_arquivo" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "taxas_bairro" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "taxas_bairro_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bairro" varchar(120) NOT NULL,
	"taxa" numeric(10, 2) DEFAULT 0 NOT NULL,
	"tempo_min" integer,
	"tempo_max" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "taxas_bairro_uniq_bairro" UNIQUE("loja_id","bairro")
);
--> statement-breakpoint
CREATE TABLE "taxas_dinamicas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "taxas_dinamicas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"distancia_km" numeric(10, 2) DEFAULT 0 NOT NULL,
	"valor" numeric(10, 2) DEFAULT 0 NOT NULL,
	"tipo" text DEFAULT 'fixa' NOT NULL,
	"tempo_min" integer,
	"tempo_max" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "versiculo_reacoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "versiculo_reacoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"admin_id" integer NOT NULL,
	"data_versiculo" date NOT NULL,
	"reacao" text NOT NULL,
	"referencia" varchar(80),
	"texto" text,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	CONSTRAINT "versiculo_reacoes_uniq_reacao_admin_data" UNIQUE("admin_id","data_versiculo")
);
--> statement-breakpoint
CREATE TABLE "whats_conversas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whats_conversas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"loja_id" integer NOT NULL,
	"numero" varchar(30) NOT NULL,
	"nome" varchar(150),
	"ultimo_msg" text,
	"ultimo_msg_em" timestamp,
	"nao_lidas" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "whats_conversas_uq_loja_numero" UNIQUE("loja_id","numero")
);
--> statement-breakpoint
CREATE TABLE "whats_mensagens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "whats_mensagens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversa_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"direcao" text NOT NULL,
	"tipo" text DEFAULT 'texto',
	"mensagem" text NOT NULL,
	"pedido_id" integer,
	"whats_msg_id" varchar(120),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "complementos_grupos_categorias" ADD CONSTRAINT "complementos_grupos_categorias_fk_comp_grupo_cat_grupo" FOREIGN KEY ("grupo_id") REFERENCES "public"."complementos_grupos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complementos_grupos_produtos" ADD CONSTRAINT "complementos_grupos_produtos_fk_comp_grupo_prod_grupo" FOREIGN KEY ("grupo_id") REFERENCES "public"."complementos_grupos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "complementos_itens" ADD CONSTRAINT "complementos_itens_fk_comp_grupo" FOREIGN KEY ("grupo_id") REFERENCES "public"."complementos_grupos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "estoque" ADD CONSTRAINT "estoque_fk_estoque_produto" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "estoque_movimentacoes" ADD CONSTRAINT "estoque_movimentacoes_fk_mov_produto" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financial_categories" ADD CONSTRAINT "financial_categories_fk_financial_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "public"."financial_categories"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_fk_financial_transactions_account" FOREIGN KEY ("account_id") REFERENCES "public"."financial_accounts"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_fk_financial_transactions_category" FOREIGN KEY ("category_id") REFERENCES "public"."financial_categories"("id") ON DELETE no action ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_fk_financial_transactions_payment_method" FOREIGN KEY ("payment_method_id") REFERENCES "public"."payment_methods"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "listas_transmissao_envios" ADD CONSTRAINT "listas_transmissao_envios_fk_lte_lista" FOREIGN KEY ("lista_id") REFERENCES "public"."listas_transmissao"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listas_transmissao_membros" ADD CONSTRAINT "listas_transmissao_membros_fk_ltm_lista" FOREIGN KEY ("lista_id") REFERENCES "public"."listas_transmissao"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orcamento_itens" ADD CONSTRAINT "orcamento_itens_orcamento_itens_ibfk_1" FOREIGN KEY ("orcamento_id") REFERENCES "public"."orcamentos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pedido_itens" ADD CONSTRAINT "pedido_itens_pedido_itens_ibfk_1" FOREIGN KEY ("pedido_id") REFERENCES "public"."pedidos"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pedido_status_log" ADD CONSTRAINT "pedido_status_log_pedido_status_log_ibfk_1" FOREIGN KEY ("pedido_id") REFERENCES "public"."pedidos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pedidos" ADD CONSTRAINT "pedidos_pedidos_ibfk_1" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "produto_complementos_itens" ADD CONSTRAINT "produto_complementos_itens_fk_produto_complementos_itens_produt" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "produto_extras" ADD CONSTRAINT "produto_extras_fk_produto_extras_produto" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "produto_variacoes" ADD CONSTRAINT "produto_variacoes_fk_produto_variacoes_produto" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_fk_produtos_categoria" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "produtos" ADD CONSTRAINT "produtos_produtos_ibfk_1" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "whats_mensagens" ADD CONSTRAINT "whats_mensagens_whats_mensagens_ibfk_1" FOREIGN KEY ("conversa_id") REFERENCES "public"."whats_conversas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "admin_api_tokens_idx_admin" ON "admin_api_tokens" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "admins_idx_admins_google_id" ON "admins" USING btree ("google_id");--> statement-breakpoint
CREATE INDEX "assinaturas_idx_assinatura_loja" ON "assinaturas" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "assinaturas_idx_assinatura_status" ON "assinaturas" USING btree ("status");--> statement-breakpoint
CREATE INDEX "caixa_movimentacoes_idx_caixa" ON "caixa_movimentacoes" USING btree ("caixa_id");--> statement-breakpoint
CREATE INDEX "caixa_movimentacoes_idx_operador" ON "caixa_movimentacoes" USING btree ("operador_id");--> statement-breakpoint
CREATE INDEX "caixa_movimentacoes_idx_data" ON "caixa_movimentacoes" USING btree ("criado_em");--> statement-breakpoint
CREATE INDEX "cashback_movimentacoes_idx_cashback_cliente" ON "cashback_movimentacoes" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "cashback_movimentacoes_idx_cashback_pedido" ON "cashback_movimentacoes" USING btree ("pedido_id");--> statement-breakpoint
CREATE INDEX "cashback_movimentacoes_idx_cashback_tipo" ON "cashback_movimentacoes" USING btree ("tipo");--> statement-breakpoint
CREATE INDEX "cashback_movimentacoes_idx_cashback_expira" ON "cashback_movimentacoes" USING btree ("expira_em");--> statement-breakpoint
CREATE INDEX "cashback_movimentacoes_idx_cashback_ref" ON "cashback_movimentacoes" USING btree ("referencia_id");--> statement-breakpoint
CREATE INDEX "cobrancas_idx_cobranca_assinatura" ON "cobrancas" USING btree ("assinatura_id");--> statement-breakpoint
CREATE INDEX "cobrancas_idx_cobranca_status" ON "cobrancas" USING btree ("status");--> statement-breakpoint
CREATE INDEX "combo_passo_opcoes_idx_cpo_passo" ON "combo_passo_opcoes" USING btree ("passo_id");--> statement-breakpoint
CREATE INDEX "combo_passo_opcoes_idx_cpo_combo" ON "combo_passo_opcoes" USING btree ("combo_id");--> statement-breakpoint
CREATE INDEX "combo_passo_opcoes_idx_cpo_loja" ON "combo_passo_opcoes" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "combo_passos_idx_cp_combo" ON "combo_passos" USING btree ("combo_id");--> statement-breakpoint
CREATE INDEX "combo_passos_idx_cp_loja" ON "combo_passos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "combos_idx_combos_loja" ON "combos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "combos_idx_combos_categoria" ON "combos" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_categorias_idx_comp_grupo_cat_grupo" ON "complementos_grupos_categorias" USING btree ("grupo_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_categorias_idx_comp_grupo_cat_cat" ON "complementos_grupos_categorias" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_categorias_idx_comp_grupo_cat_loja" ON "complementos_grupos_categorias" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_produtos_idx_comp_grupo_prod_grupo" ON "complementos_grupos_produtos" USING btree ("grupo_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_produtos_idx_comp_grupo_prod_prod" ON "complementos_grupos_produtos" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "complementos_grupos_produtos_idx_comp_grupo_prod_loja" ON "complementos_grupos_produtos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "complementos_itens_idx_comp_grupo" ON "complementos_itens" USING btree ("grupo_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_bancos_idx_entrada_saida_bancos_loja" ON "entrada_saida_bancos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_categorias_idx_entrada_saida_categorias_loja" ON "entrada_saida_categorias" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_formas_idx_entrada_saida_formas_loja" ON "entrada_saida_formas" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_lancamentos_idx_entrada_saida_lancamentos_loja" ON "entrada_saida_lancamentos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_lancamentos_idx_entrada_saida_lancamentos_data" ON "entrada_saida_lancamentos" USING btree ("data_lancamento");--> statement-breakpoint
CREATE INDEX "entrada_saida_lancamentos_idx_entrada_saida_lancamentos_tipo" ON "entrada_saida_lancamentos" USING btree ("tipo");--> statement-breakpoint
CREATE INDEX "entrada_saida_subcategorias_idx_entrada_saida_subcategorias_loj" ON "entrada_saida_subcategorias" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "entrada_saida_subcategorias_idx_entrada_saida_subcategorias_cat" ON "entrada_saida_subcategorias" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "estoque_grupo_membros_idx_egm_grupo" ON "estoque_grupo_membros" USING btree ("grupo_id","loja_id");--> statement-breakpoint
CREATE INDEX "estoque_movimentacoes_fk_mov_produto" ON "estoque_movimentacoes" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "fiado_lancamentos_idx_loja_cliente" ON "fiado_lancamentos" USING btree ("loja_id","cliente_id");--> statement-breakpoint
CREATE INDEX "financial_accounts_idx_financial_accounts_tenant" ON "financial_accounts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "financial_categories_idx_financial_categories_tenant" ON "financial_categories" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "financial_categories_idx_financial_categories_parent" ON "financial_categories" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "financial_categories_idx_financial_categories_type" ON "financial_categories" USING btree ("type");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_tenant" ON "financial_transactions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_account" ON "financial_transactions" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_category" ON "financial_transactions" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_payment_metho" ON "financial_transactions" USING btree ("payment_method_id");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_date" ON "financial_transactions" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_reference" ON "financial_transactions" USING btree ("reference_year","reference_month");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_type" ON "financial_transactions" USING btree ("type");--> statement-breakpoint
CREATE INDEX "financial_transactions_idx_financial_transactions_order" ON "financial_transactions" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "garcons_idx_garcons_loja" ON "garcons" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "leads_lojas_idx_leads_email" ON "leads_lojas" USING btree ("email");--> statement-breakpoint
CREATE INDEX "listas_transmissao_idx_lt_loja" ON "listas_transmissao" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "listas_transmissao_envios_idx_lte_lista" ON "listas_transmissao_envios" USING btree ("lista_id");--> statement-breakpoint
CREATE INDEX "listas_transmissao_membros_idx_ltm_lista" ON "listas_transmissao_membros" USING btree ("lista_id");--> statement-breakpoint
CREATE INDEX "loja_eventos_idx_loja_tipo_data" ON "loja_eventos" USING btree ("loja_id","tipo","criado_em");--> statement-breakpoint
CREATE INDEX "materia_prima_cadastros_idx_materia_prima_loja" ON "materia_prima_cadastros" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "materia_prima_cadastros_idx_materia_prima_data" ON "materia_prima_cadastros" USING btree ("data_compra");--> statement-breakpoint
CREATE INDEX "materia_prima_cadastros_idx_materia_prima_categoria" ON "materia_prima_cadastros" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "materia_prima_cadastros_idx_materia_prima_subcategoria" ON "materia_prima_cadastros" USING btree ("subcategoria_id");--> statement-breakpoint
CREATE INDEX "mesas_idx_mesas_loja" ON "mesas" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "mesas_idx_mesas_ativo" ON "mesas" USING btree ("loja_id","ativo");--> statement-breakpoint
CREATE INDEX "motoboys_idx_motoboys_loja" ON "motoboys" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "motoboys_idx_motoboys_ativo" ON "motoboys" USING btree ("loja_id","ativo");--> statement-breakpoint
CREATE INDEX "notificacoes_broadcast_idx_status" ON "notificacoes_broadcast" USING btree ("status");--> statement-breakpoint
CREATE INDEX "orcamento_itens_orcamento_id" ON "orcamento_itens" USING btree ("orcamento_id");--> statement-breakpoint
CREATE INDEX "orcamentos_idx_orcamentos_loja" ON "orcamentos" USING btree ("loja_id","criado_em");--> statement-breakpoint
CREATE INDEX "pausas_programadas_idx_loja" ON "pausas_programadas" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "payment_methods_idx_payment_methods_tenant" ON "payment_methods" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "pdv_reservas_idx_pdvres_loja_atual" ON "pdv_reservas" USING btree ("loja_id","atualizado_em");--> statement-breakpoint
CREATE INDEX "pedido_combo_itens_idx_pci_pedido" ON "pedido_combo_itens" USING btree ("pedido_id","loja_id");--> statement-breakpoint
CREATE INDEX "pedido_combo_itens_idx_pci_item" ON "pedido_combo_itens" USING btree ("pedido_item_id");--> statement-breakpoint
CREATE INDEX "pedido_itens_pedido_id" ON "pedido_itens" USING btree ("pedido_id");--> statement-breakpoint
CREATE INDEX "pedido_status_log_pedido_id" ON "pedido_status_log" USING btree ("pedido_id");--> statement-breakpoint
CREATE INDEX "pedido_status_log_idx_pedido_status_log_loja_pedido" ON "pedido_status_log" USING btree ("loja_id","pedido_id");--> statement-breakpoint
CREATE INDEX "pedidos_cliente_id" ON "pedidos" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "pedidos_idx_pedidos_motoboy" ON "pedidos" USING btree ("motoboy_id");--> statement-breakpoint
CREATE INDEX "pedidos_idx_pedidos_mesa" ON "pedidos" USING btree ("mesa_id");--> statement-breakpoint
CREATE INDEX "pedidos_idx_pedidos_garcom" ON "pedidos" USING btree ("garcom_id");--> statement-breakpoint
CREATE INDEX "permissoes_usuarios_idx_perm_admin" ON "permissoes_usuarios" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "permissoes_usuarios_idx_perm_perm" ON "permissoes_usuarios" USING btree ("permissao_id");--> statement-breakpoint
CREATE INDEX "pontos_movimentacoes_idx_pontos_cliente" ON "pontos_movimentacoes" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "pontos_movimentacoes_idx_pontos_pedido" ON "pontos_movimentacoes" USING btree ("pedido_id");--> statement-breakpoint
CREATE INDEX "pontos_movimentacoes_idx_pontos_tipo" ON "pontos_movimentacoes" USING btree ("tipo");--> statement-breakpoint
CREATE INDEX "pontos_movimentacoes_idx_pontos_ref" ON "pontos_movimentacoes" USING btree ("referencia_id");--> statement-breakpoint
CREATE INDEX "produto_complementos_itens_idx_produto_complementos_itens_produ" ON "produto_complementos_itens" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "produto_complementos_itens_idx_produto_complementos_itens_loja" ON "produto_complementos_itens" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "produto_extras_idx_produto_extras_produto" ON "produto_extras" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "produto_variacoes_idx_produto_variacoes_produto" ON "produto_variacoes" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "produtos_fk_produtos_categoria" ON "produtos" USING btree ("categoria_id");--> statement-breakpoint
CREATE INDEX "suporte_mensagens_idx_loja" ON "suporte_mensagens" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "versiculo_reacoes_idx_reacao_data" ON "versiculo_reacoes" USING btree ("data_versiculo");--> statement-breakpoint
CREATE INDEX "versiculo_reacoes_idx_reacao_admin" ON "versiculo_reacoes" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "whats_mensagens_idx_conversa" ON "whats_mensagens" USING btree ("conversa_id");