CREATE TABLE "garcom_api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "garcom_api_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"garcom_id" integer NOT NULL,
	"loja_id" integer NOT NULL,
	"token_hash" char(64) NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"expira_em" timestamp NOT NULL,
	CONSTRAINT "garcom_api_tokens_uq_token_hash" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE INDEX "garcom_api_tokens_idx_garcom" ON "garcom_api_tokens" USING btree ("garcom_id");