CREATE TABLE "produto_opcoes_grupos" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produto_opcoes_grupos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"produto_id" integer NOT NULL,
	"titulo" varchar(120) NOT NULL,
	"tipo_selecao" text DEFAULT 'unica' NOT NULL,
	"obrigatorio" boolean DEFAULT false NOT NULL,
	"ordem" integer DEFAULT 0 NOT NULL,
	"loja_id" integer NOT NULL,
	"criado_em" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "produto_opcoes_itens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "produto_opcoes_itens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grupo_id" integer NOT NULL,
	"nome" varchar(120) NOT NULL,
	"preco" numeric(10, 2) DEFAULT 0 NOT NULL,
	"ordem" integer DEFAULT 0 NOT NULL,
	"loja_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "produtos" ADD COLUMN "variacoes_titulo" varchar(120);--> statement-breakpoint
ALTER TABLE "produtos" ADD COLUMN "variacoes_obrigatorio" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "produto_opcoes_grupos" ADD CONSTRAINT "produto_opcoes_grupos_fk_produto_opcoes_grupos_produto" FOREIGN KEY ("produto_id") REFERENCES "public"."produtos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "produto_opcoes_itens" ADD CONSTRAINT "produto_opcoes_itens_fk_produto_opcoes_itens_grupo" FOREIGN KEY ("grupo_id") REFERENCES "public"."produto_opcoes_grupos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "produto_opcoes_grupos_idx_produto_opcoes_grupos_produto" ON "produto_opcoes_grupos" USING btree ("produto_id");--> statement-breakpoint
CREATE INDEX "produto_opcoes_grupos_idx_produto_opcoes_grupos_loja" ON "produto_opcoes_grupos" USING btree ("loja_id");--> statement-breakpoint
CREATE INDEX "produto_opcoes_itens_idx_produto_opcoes_itens_grupo" ON "produto_opcoes_itens" USING btree ("grupo_id");--> statement-breakpoint
-- Migra dados existentes de produto_extras/produto_complementos_itens pros novos grupos de opcoes
-- (as tabelas antigas sao derrubadas na proxima migracao, depois que a app para de le-las/escreve-las).
INSERT INTO "produto_opcoes_grupos" ("produto_id", "titulo", "tipo_selecao", "obrigatorio", "ordem", "loja_id")
SELECT "produto_id", 'Escolha seu extra', 'multipla', bool_or("obrigatorio"), 1, "loja_id"
FROM "produto_extras"
GROUP BY "produto_id", "loja_id";--> statement-breakpoint
INSERT INTO "produto_opcoes_itens" ("grupo_id", "nome", "preco", "ordem", "loja_id")
SELECT g."id", e."nome", e."preco", e."ordem", e."loja_id"
FROM "produto_extras" e
JOIN "produto_opcoes_grupos" g ON g."produto_id" = e."produto_id" AND g."titulo" = 'Escolha seu extra' AND g."loja_id" = e."loja_id";--> statement-breakpoint
INSERT INTO "produto_opcoes_grupos" ("produto_id", "titulo", "tipo_selecao", "obrigatorio", "ordem", "loja_id")
SELECT "produto_id", 'Escolha o tipo', 'unica', bool_or("obrigatorio"), 2, "loja_id"
FROM "produto_complementos_itens"
GROUP BY "produto_id", "loja_id";--> statement-breakpoint
INSERT INTO "produto_opcoes_itens" ("grupo_id", "nome", "preco", "ordem", "loja_id")
SELECT g."id", c."nome", c."preco", c."ordem", c."loja_id"
FROM "produto_complementos_itens" c
JOIN "produto_opcoes_grupos" g ON g."produto_id" = c."produto_id" AND g."titulo" = 'Escolha o tipo' AND g."loja_id" = c."loja_id";