CREATE TABLE "pedido_item_opcoes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pedido_item_opcoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pedido_item_id" integer NOT NULL,
	"tipo" text NOT NULL,
	"grupo_id" integer,
	"referencia_id" integer NOT NULL,
	"loja_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pedido_item_opcoes" ADD CONSTRAINT "pedido_item_opcoes_fk_pedido_item_opcoes_item" FOREIGN KEY ("pedido_item_id") REFERENCES "public"."pedido_itens"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pedido_item_opcoes_idx_pedido_item_opcoes_item" ON "pedido_item_opcoes" USING btree ("pedido_item_id");