CREATE TABLE "taxas_areas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "taxas_areas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"poligono" jsonb NOT NULL,
	"taxa" numeric(10, 2) DEFAULT 0 NOT NULL,
	"tempo_min" integer,
	"tempo_max" integer,
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp,
	"loja_id" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "taxas_areas_uniq_nome" UNIQUE("loja_id","nome")
);
