ALTER TABLE produtos ADD COLUMN promo_dias INT NULL DEFAULT NULL;
ALTER TABLE produtos ADD COLUMN promo_inicio DATE NULL DEFAULT NULL;
ALTER TABLE produtos ADD COLUMN promo_imagem VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE produtos ADD COLUMN promo_descricao TEXT NULL DEFAULT NULL;
