CREATE TABLE IF NOT EXISTS landing_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  chave VARCHAR(80) NOT NULL,
  valor MEDIUMTEXT NOT NULL,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_chave (chave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
