CREATE TABLE IF NOT EXISTS cupons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(15) NOT NULL UNIQUE,
  tipo ENUM('percent','valor','frete') NOT NULL DEFAULT 'percent',
  desconto DECIMAL(10,2) NOT NULL DEFAULT 0,
  minimo DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantidade_total INT NOT NULL DEFAULT 0,
  quantidade_usada INT NOT NULL DEFAULT 0,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  primeira_compra TINYINT(1) NOT NULL DEFAULT 0,
  publico TINYINT(1) NOT NULL DEFAULT 0,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
